apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cors-filter
  namespace: default # replace with your actual namespace
spec:
  workloadSelector:
    labels:
      app: django
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: envoy.cors
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"
            allow_origin_string_match:
              - prefix: "*" # replace with your actual origin if needed
            allow_methods: "GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH"
            allow_headers: "*"
            max_age: "1728000"
            expose_headers: "x-custom-header"
