apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: jaeger
spec:
  selector:
    app: jaeger-query
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 16686
  type: LoadBalancer
