apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
    spec:
      containers:
        - name: jaeger-collector
          image: jaegertracing/jaeger-collector:latest
          ports:
            - containerPort: 14250
              protocol: TCP
              name: zipkin-thrift
            - containerPort: 14267
              protocol: HTTP
              name: config-http
            - containerPort: 14268
              protocol: HTTP
              name: jaeger-http
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: "http://elasticsearch:9200"
