apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          env:
            - name: cluster.name
              value: "docker-cluster"
            - name: discovery.type
              value: single-node
