apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query
    spec:
      containers:
        - name: jaeger-query
          image: jaegertracing/jaeger-query:latest
          ports:
            - containerPort: 16686
              protocol: TCP
              name: http
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: "http://elasticsearch:9200"
