# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingredient.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ingredient.proto\x12\ningredient\"K\n\x11IngredientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\x16\n\x0e\x64\x61te_of_expiry\x18\x03 \x01(\t\"\"\n\x0fIngredientReply\x12\x0f\n\x07message\x18\x01 \x01(\t2`\n\x11IngredientService\x12K\n\rAddIngredient\x12\x1d.ingredient.IngredientRequest\x1a\x1b.ingredient.IngredientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingredient_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INGREDIENTREQUEST']._serialized_start=32
  _globals['_INGREDIENTREQUEST']._serialized_end=107
  _globals['_INGREDIENTREPLY']._serialized_start=109
  _globals['_INGREDIENTREPLY']._serialized_end=143
  _globals['_INGREDIENTSERVICE']._serialized_start=145
  _globals['_INGREDIENTSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
