apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  selector:
    app: envoy
  ports:
    - name: django
      protocol: TCP
      port: 8001
      targetPort: 8000
    - name: angular
      protocol: TCP
      port: 4201
      targetPort: 4200
  type: LoadBalancer
