apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  selector:
    app: envoy
  ports:
    - name: djano
      protocol: TCP
      port: 8081
      targetPort: 8080
    - name: angular
      protocol: TCP
      port: 8082
      targetPort: 8083
  type: LoadBalancer
