apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-deployment
  namespace: falco-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      containers:
        - name: falco-container
          image: falcosecurity/falco:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: falco-config
              mountPath: /etc/falco-config
            - name: falco-rules
              mountPath: /etc/falco-rules
      volumes:
        - name: falco-config
          configMap:
            name: falco-config
        - name: falco-rules
          configMap:
            name: falco-rules
---
apiVersion: v1
kind: Service
metadata:
  name: falco-service
  namespace: falco-stack
spec:
  selector:
    app: falco
  ports:
    - protocol: TCP
      port: 5060
      targetPort: 5060
  type: ClusterIP
