# mysql-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQ=
  database: SW5ncmVkaWVudHM=
  user: QWthc2hCYWxhbmk=
  password: SGFiaWJpSXMxMTAlTG92ZQ==
