apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: angular-container
          image: akashbalani/recipefront:latest
          ports:
            - containerPort: 4200
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: accesskeyid
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: secretaccesskey
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: awsregion
            - name: QueueUrl
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: queueurl
        # - name: envoy-sidecar
        #   image: envoyproxy/envoy:v1.19.0
        #   args:
        #     - "--config-path"
        #     - "/etc/envoy/envoy.yaml"
        #   ports:
        #     - containerPort: 4201
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: app
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      # nodePort: 30001
  type: LoadBalancer
