# django-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      initContainers:
        - name: init-django
          image: akashbalani/recipe:latest
          command: ["sh"]
          args:
            - /app/init-container.sh
          volumeMounts:
            - name: init-script-volume
              mountPath: /app/manifest
      containers:
        - name: django-container
          image: akashbalani/recipe:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: accesskeyid
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: secretaccesskey
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: awsregion
            - name: QueueUrl
              valueFrom:
                secretKeyRef:
                  name: angular-secret
                  key: queueurl
        # - name: envoy-sidecar
        #   image: akashbalani/recipeenvoy:latest
        #   command:
        #     - envoy
        #     - "--config-path"
        #     - "/etc/envoy/envoy.yaml"
        #   ports:
        #     - containerPort: 8001
      volumes:
        - name: init-script-volume
          persistentVolumeClaim:
            claimName: init-script-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: app
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30000
  type: LoadBalancer
