# pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: init-script-pv
  namespace: app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$(pwd)"
