# DISCLAIMER: DOES NOT WORK ON MACOS M1 CHIP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-deployment
  namespace: splunk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - name: splunk
          image: splunk/splunk:latest
          ports:
            - containerPort: 8099
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: splunk-service
  namespace: splunk-stack
spec:
  selector:
    app: splunk
  ports:
    - name: splunk-web
      protocol: TCP
      port: 8099
      targetPort: 8099
    - name: splunk-api
      protocol: TCP
      port: 8088
      targetPort: 8088
  type: LoadBalancer
